CREATE TABLE tbl_phil_city_municipalities
(
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    mun_code VARCHAR(255) NOT NULL UNIQUE,
    prov_code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);