CREATE TABLE tbl_ojt_delivery_modes
(
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    mode VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);