CREATE TABLE tbl_programs
(
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    department_id VARCHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    abbr VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES tbl_departments(id)
);